apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapseiq-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: synapseiq-backend
  template:
    metadata:
      labels:
        app: synapseiq-backend
    spec:
      containers:
      - name: synapseiq-backend
        image: synapseiq-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: synapseiq-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: synapseiq-backend-service
spec:
  type: ClusterIP
  selector:
    app: synapseiq-backend
  ports:
  - port: 8000
    targetPort: 8000
